version: '3'
services:
  redis:
    image: 'redis'
    command: redis-server
    volumes:
      - 'redis:/data'
  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./worker.rb
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    depends_on:
      - redis
  sidekiq-web:
    build: .
    command: rackup config.ru -o 0.0.0.0 -p 3030 -q
    volumes:
      - '.:/app'
    depends_on:
      - redis
      - sidekiq
    ports:
      - '3030:3030'
volumes:
  redis:

  